// src/MyApp.vue
<template>
	<div class="hello-world">
		<h1 class="title">{{ message }}</h1>
		<MyButton />
	</div>
</template>

<script setup>
import MyButton from './MyButton.vue';
import { ref } from 'vue';

const msg = 'Hello World !';
const message = ref(msg);
</script>

<style lang="stylus">
.hello-world
	background-color: #f0f0f0;
	.title
		color blue
</style>

// src/frameworks/web/react/components/MyApp.tsx
import { useState } from 'react';
import MyButton from '@webreact/components/MyButton';
import './MyApp.styl';

export default function MyApp() {
	const msg: string = 'Hello World !';
	const [message]: [string, (value: string) => void] = useState(msg);

	return (
		<div className="hello-world">
			<h1 className="title">{message}</h1>
			<MyButton />
		</div>
	);
}
