// src/frameworks/web/react/components/MyButton.tsx
import { useState } from 'react';
import './MyButton.styl';

export default function MyButton() {
	const [message, setMessage]: [string, (value: string) => void] = useState('Click me');

	const click: () => void = () => {
		setMessage('Clicked');
	};

	return (
		<>
			<button className="my-button" onClick={click}>
				{message} !
			</button>
			<input
				type="text"
				value={message}
				onChange={(e) => setMessage(e.target.value)}
			/>
		</>
	);
}

// src/MyButton.vue
<template>
	<button class="my-button" @click="click">{{ message }} !</button>
	<input type="text" v-model="message" />
</template>

<script setup>
import { ref } from 'vue';

const message = ref('Click me');

const click = () => {
	message.value = 'Clicked';
};
</script>

<style lang="stylus">
.my-button
	color green
</style>
